apiVersion: v1
kind: Service
metadata:
  name: web-java-app-service-uat
  namespace: uat
spec:
  type: NodePort
  selector:
    app: web-java-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31080

